-- CREAR LA BASE DE DATOS
CREATE DATABASE MARZEL;
GO
USE MARZEL;
GO
/****** OBJECT:  TABLE TBL_ESTADOS_USUARIO ******/
CREATE TABLE TBL_ESTADOS_USUARIO(
	ID_ESTADO INT IDENTITY(1,1) NOT NULL,
	DESCRIPCION VARCHAR(25) NOT NULL,
);

--PK
ALTER TABLE TBL_ESTADOS_USUARIO ADD CONSTRAINT PK_ESTADOS_USUARIO
PRIMARY KEY(ID_ESTADO);

/****** OBJECT:  TABLE TBL_TIPOS_USUARIO ******/
CREATE TABLE TBL_TIPOS_USUARIO(
	ID_TIPO INT IDENTITY(1,1) NOT NULL,
	DESCRIPCION VARCHAR(25) NOT NULL,
);

--PK
ALTER TABLE TBL_TIPOS_USUARIO ADD CONSTRAINT PK_TIPOS_USUARIO
PRIMARY KEY(ID_TIPO);

/****** OBJECT:  TABLE TBL_USUARIOS ******/
CREATE TABLE TBL_USUARIOS(
	ID_USUARIO INT IDENTITY(1,1) NOT NULL,
	IDENTIDAD VARCHAR(13) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	CORREO VARCHAR(50) NOT NULL,
	USUARIO VARCHAR(50) NOT NULL,
	CONTRASENA VARCHAR(50) NOT NULL,
	CELULAR VARCHAR(8) NOT NULL,
	ID_TIPO INT NOT NULL,
	ID_ESTADO INT NOT NULL,
);

--PK
ALTER TABLE TBL_USUARIOS ADD CONSTRAINT PK_USUARIOS
PRIMARY KEY(ID_USUARIO);

--UQ
ALTER TABLE TBL_USUARIOS ADD CONSTRAINT UQ_USUARIOS_IDENTIDAD
UNIQUE(IDENTIDAD);

ALTER TABLE TBL_USUARIOS ADD CONSTRAINT UQ_USUARIOS_CORREO
UNIQUE(CORREO);

ALTER TABLE TBL_USUARIOS ADD CONSTRAINT UQ_USUARIOS_USUARIO
UNIQUE(USUARIO);

--FK
ALTER TABLE TBL_USUARIOS ADD CONSTRAINT FK_USUARIOS_TIPOS_USUARIO
FOREIGN KEY(ID_TIPO) REFERENCES TBL_TIPOS_USUARIO(ID_TIPO);

ALTER TABLE TBL_USUARIOS ADD CONSTRAINT FK_USUARIOS_ESTADOS_USUARIO
FOREIGN KEY(ID_ESTADO) REFERENCES TBL_ESTADOS_USUARIO(ID_ESTADO);

/****** OBJECT:  TABLE TBL_PROVEEDORES ******/
CREATE TABLE TBL_PROVEEDORES(
	ID_PROVEEDOR INT IDENTITY(1,1) NOT NULL,
	RTN VARCHAR(14) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(50) NULL,
	CELULAR VARCHAR(8) NULL,
	CANT_COMPRAS INT NULL,
	IMPORTE DECIMAL(9, 2) NULL
); 

--PK
ALTER TABLE TBL_PROVEEDORES ADD CONSTRAINT PK_PROVEEDORES
PRIMARY KEY(ID_PROVEEDOR);

--UQ
ALTER TABLE TBL_PROVEEDORES ADD CONSTRAINT UQ_PROVEEDORES_RTN
UNIQUE(RTN);

/****** OBJECT:  TABLE TBL_COMPRAS ******/
CREATE TABLE TBL_COMPRAS(
	ID_COMPRA INT IDENTITY(1,1) NOT NULL,
	ID_PROVEEDOR INT NOT NULL,
	FECHA DATE NOT NULL,
	FACTURA VARCHAR(25) NOT NULL,
	SUBTOTAL DECIMAL(9, 2) NOT NULL,
	GRAVADO DECIMAL(9, 2) NOT NULL,
	ISV DECIMAL(9, 2) NOT NULL,
	EXENTO DECIMAL(9, 2) NOT NULL,
	TOTAL DECIMAL(9, 2) NOT NULL
);

--PK
ALTER TABLE TBL_COMPRAS ADD CONSTRAINT PK_COMPRAS
PRIMARY KEY(ID_COMPRA);

--UQ
ALTER TABLE TBL_COMPRAS ADD CONSTRAINT UQ_COMPRAS_FACTURA
UNIQUE(FACTURA);

--FK
ALTER TABLE TBL_COMPRAS ADD CONSTRAINT FK_COMPRAS_PROVEEDORES
FOREIGN KEY(ID_PROVEEDOR) REFERENCES TBL_PROVEEDORES(ID_PROVEEDOR);

/****** OBJECT:  TABLE TBL_CATEGORIAS_PRODUCTO ******/
CREATE TABLE TBL_CATEGORIAS_PRODUCTO(
	ID_CATEGORIA INT IDENTITY(1,1) NOT NULL,
	DESCRIPCION VARCHAR(25) NOT NULL
);

--PK
ALTER TABLE TBL_CATEGORIAS_PRODUCTO ADD CONSTRAINT PK_CATEGORIAS_PRODUCTO
PRIMARY KEY(ID_CATEGORIA);

/****** OBJECT:  TABLE TBL_TIPOS_ISV ******/
CREATE TABLE TBL_TIPOS_ISV(
	ID_ISV INT IDENTITY(1,1) NOT NULL,
	DESCRIPCION VARCHAR(2) NOT NULL,
);

--PK
ALTER TABLE TBL_TIPOS_ISV ADD CONSTRAINT PK_TIPOS_ISV
PRIMARY KEY(ID_ISV);

/****** OBJECT:  TABLE TBL_PRODUCTOS ******/
CREATE TABLE TBL_PRODUCTOS(
	ID_PRODUCTO INT IDENTITY(1,1) NOT NULL,
	CODIGO_BARRA VARCHAR(25) NOT NULL,
	DESCRIPCION VARCHAR(100) NOT NULL,
	ID_ISV INT NOT NULL,
	PRECIO_COMPLETO DECIMAL(9, 2) NULL,
	PRECIO_UNITARIO DECIMAL(9, 2) NULL,
	ID_CATEGORIA INT NOT NULL,
	EXISTENCIA INT NOT NULL,
);

--PK
ALTER TABLE TBL_PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS
PRIMARY KEY(ID_PRODUCTO);

--UQ
ALTER TABLE TBL_PRODUCTOS ADD CONSTRAINT UQ_PRODUCTOS_CODIGO_BARRA
UNIQUE(CODIGO_BARRA);

--FK
ALTER TABLE TBL_PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_TIPOS_ISV
FOREIGN KEY(ID_ISV) REFERENCES TBL_TIPOS_ISV(ID_ISV);

ALTER TABLE TBL_PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_CATEGORIAS_PRODUCTO
FOREIGN KEY(ID_CATEGORIA) REFERENCES TBL_CATEGORIAS_PRODUCTO(ID_CATEGORIA);

/****** OBJECT:  TABLE TBL_DETALLES_COMPRA ******/
CREATE TABLE TBL_DETALLES_COMPRA(
	ID_COMPRA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	COSTO DECIMAL(9, 2) NOT NULL,
	DESCUENTO DECIMAL(9, 2) NOT NULL,
	IMPORTE DECIMAL(9, 2) NOT NULL,
);

--PK
ALTER TABLE TBL_DETALLES_COMPRA ADD CONSTRAINT PK_DETALLES_COMPRA
PRIMARY KEY(ID_COMPRA, ID_PRODUCTO);

--FK
ALTER TABLE TBL_DETALLES_COMPRA ADD CONSTRAINT FK_DETALLES_COMPRA_COMPRAS
FOREIGN KEY(ID_COMPRA) REFERENCES TBL_COMPRAS(ID_COMPRA);

ALTER TABLE TBL_DETALLES_COMPRA ADD CONSTRAINT FK_DETALLES_COMPRA_PRODUCTOS
FOREIGN KEY(ID_PRODUCTO) REFERENCES TBL_PRODUCTOS(ID_PRODUCTO);

/****** OBJECT:  TABLE TBL_CLIENTES ******/
CREATE TABLE TBL_CLIENTES(
	ID_CLIENTE INT IDENTITY(1,1) NOT NULL,
	RTN VARCHAR(14) NOT NULL,
	NOMBRE VARCHAR(50) NOT NULL,
	DIRECCION VARCHAR(50) NULL,
	CELULAR VARCHAR(8) NULL,
	CANT_COMPRAS INT NULL,
	IMPORTE DECIMAL(9, 2) NULL
);

--PK
ALTER TABLE TBL_CLIENTES ADD CONSTRAINT PK_CLIENTES
PRIMARY KEY(ID_CLIENTE);

--UQ
ALTER TABLE TBL_CLIENTES ADD CONSTRAINT UQ_CLIENTES_RTN
UNIQUE(RTN);

/****** OBJECT:  TABLE TBL_VENTAS ******/
CREATE TABLE TBL_VENTAS(
	ID_VENTA INT IDENTITY(1,1) NOT NULL,
	ID_USUARIO INT NOT NULL,
	ID_CLIENTE INT NOT NULL,
	FECHA DATE NOT NULL,
	FACTURA VARCHAR(25) NOT NULL,
	SUBTOTAL DECIMAL(9, 2) NOT NULL,
	GRAVADO DECIMAL(9, 2) NOT NULL,
	ISV DECIMAL(9, 2) NOT NULL,
	EXENTO DECIMAL(9, 2) NOT NULL,
	TOTAL DECIMAL(9, 2) NOT NULL,
);

--PK
ALTER TABLE TBL_VENTAS ADD CONSTRAINT PK_VENTAS
PRIMARY KEY(ID_VENTA);

--UQ
ALTER TABLE TBL_VENTAS ADD CONSTRAINT UQ_VENTAS_FACTURA
UNIQUE(FACTURA);

--FK
ALTER TABLE TBL_VENTAS ADD CONSTRAINT FK_VENTAS_USUARIOS
FOREIGN KEY(ID_USUARIO) REFERENCES TBL_USUARIOS(ID_USUARIO);

ALTER TABLE TBL_VENTAS ADD CONSTRAINT FK_VENTAS_CLIENTES
FOREIGN KEY(ID_CLIENTE) REFERENCES TBL_CLIENTES(ID_CLIENTE);

/****** OBJECT:  TABLE TBL_DETALLES_VENTA ******/
CREATE TABLE TBL_DETALLES_VENTA(
	ID_VENTA INT NOT NULL,
	ID_PRODUCTO INT NOT NULL,
	CANTIDAD INT NOT NULL,
	COSTO DECIMAL(9, 2) NOT NULL,
	DESCUENTO DECIMAL(9, 2) NOT NULL,
	IMPORTE DECIMAL(9, 2) NOT NULL,
);

--PK
ALTER TABLE TBL_DETALLES_VENTA ADD CONSTRAINT PK_DETALLES_VENTA
PRIMARY KEY(ID_VENTA, ID_PRODUCTO);

--FK
ALTER TABLE TBL_DETALLES_VENTA ADD CONSTRAINT FK_DETALLES_VENTA_VENTAS
FOREIGN KEY(ID_VENTA) REFERENCES TBL_VENTAS(ID_VENTA);

ALTER TABLE TBL_DETALLES_VENTA ADD CONSTRAINT FK_DETALLES_VENTA_PRODUCTOS
FOREIGN KEY(ID_PRODUCTO) REFERENCES TBL_PRODUCTOS(ID_PRODUCTO);

/****** OBJECT:  TABLE TEMP_COMPRAS ******/
CREATE TABLE TEMP_COMPRAS(
	ID_COMPRA INT NULL,
	ID_PROVEEDOR INT NULL,
	RTN VARCHAR(14) NULL,
	NOMBRE VARCHAR(50) NULL,
	DIRECCION VARCHAR(50) NULL,
	CELULAR VARCHAR(8) NULL,
	FECHA DATE NULL,
	FACTURA VARCHAR(25) NULL,
	SUBTOTAL DECIMAL(9, 2) NULL,
	GRAVADO DECIMAL(9, 2) NULL,
	ISV DECIMAL(9, 2) NULL,
	EXENTO DECIMAL(9, 2) NULL,
	TOTAL DECIMAL(9, 2) NULL
);

/****** OBJECT:  TABLE TEMP_DETALLES_COMPRA ******/
CREATE TABLE TEMP_DETALLES_COMPRA(
	ID_COMPRA INT NULL,
	ID_PRODUCTO INT NULL,
	CODIGO_BARRA VARCHAR(25) NULL,
	DESCRIPCION VARCHAR(100) NULL,
	CANTIDAD INT NULL,
	COSTO DECIMAL(9, 2) NULL,
	ID_ISV INT NULL,
	DESCUENTO DECIMAL(9, 2) NULL,
	IMPORTE DECIMAL(9, 2) NULL,
	PRECIO_COMPLETO DECIMAL(9, 2) NULL,
	PRECIO_UNITARIO DECIMAL(9, 2) NULL,
	ID_CATEGORIA INT NULL,
	FECHA_CREACION DATE NULL
);

CREATE TABLE TBL_MOVIMIENTOS_INVENTARIO (
	ID_MOVIMIENTO INT IDENTITY(1,1) NOT NULL,
	NOMBRE_PRODUCTO VARCHAR(100) NOT NULL,
	FECHA DATE NOT NULL,
	TIPO_MOVIMIENTO VARCHAR(10) NOT NULL, -- 'ENTRADA' o 'SALIDA'
	CANTIDAD INT NOT NULL,
	NOMBRE_USUARIO VARCHAR(50) NOT NULL
);

-- PK
ALTER TABLE TBL_MOVIMIENTOS_INVENTARIO ADD CONSTRAINT PK_MOVIMIENTOS_INVENTARIO
PRIMARY KEY(ID_MOVIMIENTO);

CREATE PROCEDURE REGISTRAR_MOVIMIENTO_INVENTARIO
	@ID_PRODUCTO INT,
	@TIPO_MOVIMIENTO VARCHAR(10), -- 'ENTRADA' o 'SALIDA'
	@CANTIDAD INT,
	@ID_USUARIO INT
AS
BEGIN
	SET NOCOUNT ON;

	-- Obtener nombre del producto
	DECLARE @NOMBRE_PRODUCTO VARCHAR(100);
	SELECT @NOMBRE_PRODUCTO = DESCRIPCION FROM TBL_PRODUCTOS WHERE ID_PRODUCTO = @ID_PRODUCTO;

	-- Obtener nombre del usuario
	DECLARE @NOMBRE_USUARIO VARCHAR(50);
	SELECT @NOMBRE_USUARIO = NOMBRE FROM TBL_USUARIOS WHERE ID_USUARIO = @ID_USUARIO;

	-- Insertar movimiento en la bitácora
	INSERT INTO TBL_MOVIMIENTOS_INVENTARIO (
		NOMBRE_PRODUCTO,
		FECHA,
		TIPO_MOVIMIENTO,
		CANTIDAD,
		NOMBRE_USUARIO
	)
	VALUES (
		@NOMBRE_PRODUCTO,
		GETDATE(),
		@TIPO_MOVIMIENTO,
		@CANTIDAD,
		@NOMBRE_USUARIO
	);
END;


-- TBL_ESTADOS_USUARIO
INSERT INTO TBL_ESTADOS_USUARIO(DESCRIPCION)
VALUES 
('ACTIVO'),
('INACTIVO');

-- TBL_TIPOS_USUARIO
INSERT INTO TBL_TIPOS_USUARIO(DESCRIPCION)
VALUES 
('ADMINISTRADOR'),
('CAJERO');

-- TBL_USUARIOS (ID_TIPO = 1 y 2; ID_ESTADO = 1)
INSERT INTO TBL_USUARIOS (IDENTIDAD, NOMBRE, CORREO, USUARIO, CONTRASENA, CELULAR, ID_TIPO, ID_ESTADO)
VALUES 
('0801199901234', 'CARLOS PÉREZ', 'CARLOS@EMPRESA.COM', 'CPEREZ', '1234', '99887755', 1, 1),
('0801199705678', 'ANA TORRES', 'ANA@EMPRESA.COM', 'ATORRES', '5678', '88776644', 2, 1),
('0319199812345', 'FEDERICO RIVERA', 'FEDE@EMPRESA.COM', '0', '0', '98745632', 1, 1);

-- TBL_PROVEEDORES
INSERT INTO TBL_PROVEEDORES (RTN, NOMBRE, DIRECCION, CELULAR, CANT_COMPRAS, IMPORTE)
VALUES 
('08011990000123', 'DISTRIBUIDORA LATINA', 'COL. KENNEDY', '99887766', 5, 12500.50),
('08011985000234', 'PROVEEDORA MUNDIAL', 'CENTRO', '88776655', 2, 5200.00);

-- TBL_COMPRAS (ID_PROVEEDOR = 1 Y 2)
INSERT INTO TBL_COMPRAS (ID_PROVEEDOR, FECHA, FACTURA, SUBTOTAL, GRAVADO, ISV, EXENTO, TOTAL)
VALUES 
(1, '2025-07-10', 'F-2025-0001', 4000.00, 4000.00, 600.00, 0.00, 4600.00),
(2, '2025-07-11', 'F-2025-0002', 1300.00, 1300.00, 195.00, 0.00, 1495.00);

-- TBL_CATEGORIAS_PRODUCTO
INSERT INTO TBL_CATEGORIAS_PRODUCTO(DESCRIPCION)
VALUES 
('ELECTRÓNICA'),
('PAPELERÍA');

-- TBL_TIPOS_ISV
INSERT INTO TBL_TIPOS_ISV (DESCRIPCION)
VALUES 
('15'),
('E');

-- TBL_PRODUCTOS (ID_ISV=1 Y 2, ID_CATEGORIA=1 Y 2)
INSERT INTO TBL_PRODUCTOS (CODIGO_BARRA, DESCRIPCION, ID_ISV, PRECIO_COMPLETO, PRECIO_UNITARIO, ID_CATEGORIA, EXISTENCIA)
VALUES 
('1234567890123', 'IMPRESORA EPSON L3250', 1, 4500.00, 4000.00, 1, 10),
('3210987654321', 'RESMA DE PAPEL A4', 2, 150.00, 130.00, 2, 100);

-- TBL_DETALLES_COMPRA (ID_COMPRA = 1 Y 2, ID_PRODUCTO = 1 Y 2)
INSERT INTO TBL_DETALLES_COMPRA (ID_COMPRA, ID_PRODUCTO, CANTIDAD, COSTO, DESCUENTO, IMPORTE)
VALUES 
(1, 1, 1, 4000.00, 0.00, 4000.00),
(2, 2, 10, 130.00, 0.00, 1300.00);

-- TBL_CLIENTES
INSERT INTO TBL_CLIENTES (RTN, NOMBRE, DIRECCION, CELULAR, CANT_COMPRAS, IMPORTE)
VALUES 
('08011991001234', 'JAVIER MEDINA', 'COL. MIRAFLORES', '98765432', 3, 3500.00),
('08011992004567', 'MARÍA LÓPEZ', 'BARRIO ABAJO', '91234567', 1, 1250.00);

-- TBL_VENTAS (ID_USUARIO=1 Y 2, ID_CLIENTE=1 Y 2)
INSERT INTO TBL_VENTAS (ID_USUARIO, ID_CLIENTE, FECHA, FACTURA, SUBTOTAL, GRAVADO, ISV, EXENTO, TOTAL)
VALUES 
(1, 1, '2025-07-12', 'V-0001-2025', 4000.00, 4000.00, 600.00, 0.00, 4600.00),
(2, 2, '2025-07-13', 'V-0002-2025', 1300.00, 1300.00, 195.00, 0.00, 1495.00);

-- TBL_DETALLES_VENTA
INSERT INTO TBL_DETALLES_VENTA (ID_VENTA, ID_PRODUCTO, CANTIDAD, COSTO, DESCUENTO, IMPORTE)
VALUES 
(1, 1, 1, 4000.00, 0.00, 4000.00),
(2, 2, 10, 130.00, 0.00, 1300.00);
