name: Build WinForms App (.NET Framework)

on:
  workflow_dispatch:
  push:
    branches: [DEV]
  pull_request:
    branches: [DEV]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore Prototipo_MarZel.sln

    - name: Build solution
      run: msbuild Prototipo_MarZel.sln /p:Configuration=Release
    
    - name: Run unit tests
      run: dotnet test  Prototipo_MarZel/Prototipo_MarZel.csproj

    - name: Configure Git user
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Create and push changes to QA
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git checkout -b temp-build-qa
        git add .
        git commit -m "Build automatizado: Push a QA desde ${{ github.ref_name }}"
        git push https://x-access-token:${TOKEN}@github.com/${{ github.repository }} temp-build-qa:QA --force
    

