name: Build WinForms App (.NET Framework)

on:
  workflow_dispatch:
  push:
    branches: [main, DEV, QA, produccion]
  pull_request:
    branches: [main, DEV, QA, produccion]

jobs:
  build:
    name: Build on Windows
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore MarZel.sln

    - name: Build solution
      run: msbuild Prototipo_MarZel.sln /p:Configuration=Release
